global:
  authority-config:
    nameservers:
      - nameserver.example.com
    mailbox: email.example.com
  listen:
    - :8053
  prometheus-listen: :9001

rdns:
  - ip_version: 6
    suffix: v6.ip.example.com
    subnets:
      - c.f.ip6.arpa
      - d.f.ip6.arpa
  - ip_version: 4
    suffix: v4.ip.example.com
    subnets:
      - 10.in-addr.arpa
      - 168.192.in-addr.arpa

resolvers:
  - zone: .
    max-connections: 100
    cache-size: 20480
    nameservers:
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.8.8:853"
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.4.4:853"
    allow-only-from-private: true

localizers:
  x.example.com:
  - 0.0.0.123/16

static-zones:
  static.example.com: static.example.com.db
