global:
  authority-config:
    nameservers:
      - nameserver.example.com
    mailbox: email.example.com
  listen:
    - :8053
  prometheus-listen: :9001

rdns:
  - ip_version: 6
    suffix: v6.ip.example.com
    subnets:
      - fc00::/7
  - ip_version: 4
    suffix: v4.ip.example.com
    subnets:
      - 10.0.0.0/8
      - 192.168.0.0/16

resolvers:
  - zone: .
    cache-size: 20480
    nameserver-strategy: random
    nameservers:
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.8.8:853"
        max-parallel-queries: 10
        timeout: 200ms
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.4.4:853"
        max-parallel-queries: 10
        timeout: 200ms
    allow-only-from-private: true

localizers:
  - zone: x.example.com
    subnets:
      - 0.0.0.123/16
    rewrites:
      - from: 10.100.0.0/16
        to: 10.2.0.0

static-zones:
  - zone: static.example.com
    file: static.example.com.db

ad-lists:
  block-lists:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  refresh-interval: 24h
