global:
  nameservers:
    - nameserver.example.com
  mailbox: email.example.com
  listen:
    - :8053

rdns:
  - ip_version: 6
    suffix: v6.ip.example.com
    subnets:
      - c.f.ip6.arpa
      - d.f.ip6.arpa
  - ip_version: 4
    suffix: v4.ip.example.com
    subnets:
      - 10.in-addr.arpa
      - 168.192.in-addr.arpa

resolvers:
  - zone: .
    nameservers: [8.8.8.8, 8.8.4.4]

localizers:
  x.example.com:
  - 0.0.0.123/16
